"""create clean_event table + constraints

Revision ID: 8f6db418ab70
Revises: 97c813a0e571
Create Date: 2025-09-15 13:22:36.476074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6db418ab70'
down_revision: Union[str, Sequence[str], None] = '97c813a0e571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_daily_date_source'), table_name='metric_daily')
    op.drop_index(op.f('ix_metric_daily_metric'), table_name='metric_daily')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_metric_daily_metric'), 'metric_daily', ['metric'], unique=False)
    op.create_index(op.f('ix_metric_daily_date_source'), 'metric_daily', ['metric_date', 'source_id'], unique=False)
    # ### end Alembic commands ###
