"""Add MetricDaily table

Revision ID: beaed7f34243
Revises: 7ba82119ad85
Create Date: 2025-09-12 14:36:03.616405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beaed7f34243'
down_revision: Union[str, Sequence[str], None] = '7ba82119ad85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_daily',
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value_sum',   sa.Numeric(18, 4), nullable=False, server_default=sa.text('0')),
    sa.Column('value_avg',   sa.Numeric(18, 4), nullable=False, server_default=sa.text('0')),
    sa.Column('value_count', sa.Integer(),      nullable=False, server_default=sa.text('0')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('metric_date', 'source_id', 'metric', name='pk_metric_daily')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric_daily')
    # ### end Alembic commands ###
