"""Week 11 baseline schema reset

Revision ID: 20251104_0001
Revises: 
Create Date: 2025-11-04 15:08:00.060619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251104_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast_reliability_fold')
    op.drop_index(op.f('ix_forecast_reliability_as_of_date'), table_name='forecast_reliability')
    op.drop_index(op.f('ix_forecast_reliability_metric'), table_name='forecast_reliability')
    op.drop_index(op.f('ix_forecast_reliability_source_name'), table_name='forecast_reliability')
    op.drop_table('forecast_reliability')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_reliability',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_name', sa.VARCHAR(), nullable=False),
    sa.Column('metric', sa.VARCHAR(), nullable=False),
    sa.Column('as_of_date', sa.DATE(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('mape', sa.FLOAT(), nullable=False),
    sa.Column('rmse', sa.FLOAT(), nullable=False),
    sa.Column('smape', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_reliability_source_name'), 'forecast_reliability', ['source_name'], unique=False)
    op.create_index(op.f('ix_forecast_reliability_metric'), 'forecast_reliability', ['metric'], unique=False)
    op.create_index(op.f('ix_forecast_reliability_as_of_date'), 'forecast_reliability', ['as_of_date'], unique=False)
    op.create_table('forecast_reliability_fold',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reliability_id', sa.INTEGER(), nullable=True),
    sa.Column('fold_index', sa.INTEGER(), nullable=False),
    sa.Column('mae', sa.FLOAT(), nullable=False),
    sa.Column('rmse', sa.FLOAT(), nullable=False),
    sa.Column('mape', sa.FLOAT(), nullable=False),
    sa.Column('bias', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['reliability_id'], ['forecast_reliability.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
