"""baseline: sources, raw_events, clean_events, metric_daily

Revision ID: 3d35f200e596
Revises: 
Create Date: 2025-09-15 15:43:14.696295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d35f200e596'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_table('clean_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'ts', 'metric', name='uq_clean_events_src_ts_metric')
    )
    op.create_index('ix_clean_events_source_id', 'clean_events', ['source_id'], unique=False)
    op.create_index('ix_clean_events_ts', 'clean_events', ['ts'], unique=False)
    op.create_table('metric_daily',
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value_sum', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('value_avg', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('value_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('metric_date', 'source_id', 'metric', name='pk_metric_daily')
    )
    op.create_table('raw_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_events_id'), 'raw_events', ['id'], unique=False)
    op.create_index(op.f('ix_raw_events_received_at'), 'raw_events', ['received_at'], unique=False)
    op.create_index(op.f('ix_raw_events_source_id'), 'raw_events', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_events_source_id'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_received_at'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_id'), table_name='raw_events')
    op.drop_table('raw_events')
    op.drop_table('metric_daily')
    op.drop_index('ix_clean_events_ts', table_name='clean_events')
    op.drop_index('ix_clean_events_source_id', table_name='clean_events')
    op.drop_table('clean_events')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
